
server:
  port: 9696

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  application:
    name: chatai-server

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatai?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1

chat:
  accessKeyId: "LTAI5tLPuVAYuoWdB4j3aAhf"
  accessKeySecret: "0hzUuKooKsMpxfOeudENX2n6qK11HZ"
  agentKey: "b254d0bfb85f4374bf0aa85bf8ca87c8_p_efm"
  appId: "e27ffb03fdc3452abaa8d61e0d680937"